import { FORM_FIELDS } from "@/components/app/form-input/form.types";

export const formFields: (FORM_FIELDS & {
	section: string;
	section_slug: "ticket-details" | "advanced-settings";
})[] = [
	{
		section: "Ticket Details",
		section_slug: "ticket-details",
		name: "name",
		type: "text",
		label: "Ticket Name",
		placeholder: "e.g., Regular",
		containerStyle: "col-span-full",
		required: true,
	},
	{
		section: "Ticket Details",
		section_slug: "ticket-details",
		name: "description",
		type: "textarea",
		label: "Ticket Note(Optional)",
		placeholder: "Enter Ticket Note (5-50 characters)",
		containerStyle: "col-span-full",
		required: false,
		note: "Extra information you want attendees to know about the ticket",
	},
	{
		section: "Ticket Details",
		section_slug: "ticket-details",
		name: "price",
		type: "text",
		label: "Ticket Price",
		placeholder: "Enter Ticket Price",
		containerStyle: "col-span-full",
		required: true,
	},
	{
		section: "Ticket Details",
		section_slug: "ticket-details",
		name: "perks",
		type: "textarea",
		label: "Perks",
		placeholder: "Enter Perks, separated by a comma",
		required: true,
		note: "Separate each perk with a comma",
	},

	{
		section: "Ticket Details",
		section_slug: "ticket-details",
		name: "total_quantity",
		type: "number",
		label: "Total Quantity",
		placeholder: "Enter Total Quantity",
		containerStyle: "col-span-full",
		required: true,
	},

	{
		section: "Advanced Settings",
		section_slug: "advanced-settings",
		name: "minimum_quantity",
		type: "number",
		label: "Min. Purchase Quantity",
		placeholder: "Enter Minimum Quantity",
		required: true,
	},
	{
		section: "Advanced Settings",
		section_slug: "advanced-settings",
		name: "maximum_quantity",
		type: "number",
		label: "Max. Purchase Quantity",
		placeholder: "Enter Maximum Quantity",
		required: false,
	},

	{
		section: "Advanced Settings",
		section_slug: "advanced-settings",
		name: "sales_start_date",
		type: "date",
		label: "Sales Start",
		placeholder: "Select Sales Start",
		required: true,
	},
	{
		section: "Advanced Settings",
		section_slug: "advanced-settings",
		name: "sales_start_time",
		type: "time",
		label: "Sales Start Time",
		placeholder: "Select Sales Start Time",
		required: false,
	},
	{
		section: "Advanced Settings",
		section_slug: "advanced-settings",
		name: "sales_end_date",
		type: "date",
		label: "Sales End",
		placeholder: "Select Sales End",
		required: false,
	},
	{
		section: "Advanced Settings",
		section_slug: "advanced-settings",
		name: "sales_end_time",
		type: "time",
		label: "Sales End Time",
		placeholder: "Select Sales End Time",
		required: false,
	},
	{
		section: "Advanced Settings",
		section_slug: "advanced-settings",
		name: "expires_at",
		type: "date",
		label: "Expires At",
		placeholder: "Select Expires At",
		containerStyle: "col-span-full",
		required: false,
		note: "The ticket will be expired after this date, if you leave it blank, the ticket will expire when the event ends",
	},
];
